repos:
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        description: 'Bandit is a tool for finding common security issues in Python code'
        entry: bandit
        language: python
        language_version: python3
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
        language: system
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true